name: primeiro-workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v5

    - name: Mensagem de Início
      run: echo "🚀 Iniciando o processo de build do projeto Java..."
    - name: Listar arquivos na raiz (pós-checkout)
      run: ls -la
    - name: Configurar JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: Compilar com javac
      run: |
        mkdir -p bin
        # Compila o arquivo Main.java dentro da pasta src/main/
        javac -d bin src/model/Paciente.java

    - name: Executar a aplicação
      run: |
        # Como o pacote é 'model', chamamos 'model.Paciente' (pacote.Classe)
        java -cp bin model.Paciente
